version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: parkit_postgres
    environment:
      POSTGRES_DB: parkit_db
      POSTGRES_USER: parkit_user
      POSTGRES_PASSWORD: parkit_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parkit_network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: parkit_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - parkit_network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: parkit_backend
    environment:
      DATABASE_URL: postgresql://parkit_user:parkit_password@postgres:5432/parkit_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 4000
      NODE_ENV: development
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - parkit_network
    command: yarn dev

  # Web App
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: parkit_web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/graphql
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - parkit_network
    command: yarn dev

  # Mobile App (Expo)
  mobile:
    build:
      context: .
      dockerfile: apps/mobile/Dockerfile
    container_name: parkit_mobile
    environment:
      EXPO_PUBLIC_API_URL: http://localhost:4000/graphql
      NODE_ENV: development
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./apps/mobile:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - parkit_network
    command: yarn start

  # Prisma Studio (Database GUI)
  prisma-studio:
    build:
      context: .
      dockerfile: packages/database/Dockerfile
    container_name: parkit_prisma_studio
    environment:
      DATABASE_URL: postgresql://parkit_user:parkit_password@postgres:5432/parkit_db
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    networks:
      - parkit_network
    command: yarn studio

volumes:
  postgres_data:
  redis_data:

networks:
  parkit_network:
    driver: bridge 